<?xml version="1.0" encoding="ISO-8859-1"?>
<project name="odiem" default="jar">

	<property file="./build.properties" />
	<property name="jarfile" value="${ant.project.name}_v${version}.jar" />

	<path id="lib.classpath">
		<fileset dir="lib">
			<include name="**/*.jar" />
		</fileset>
	</path>

	<target name="clean">
		<delete dir="${build}" />
		<delete dir="${dist}" />
	</target>

	<target name="init" depends="clean">
		<mkdir dir="${build}" />
		<mkdir dir="${dist}" />
	</target>

	<target name="build" depends="init">
		<javac srcdir="${src}" destdir="${build}"
			debug="${debug}" debuglevel="lines,vars,source"
			target="1.5" source="1.5" includeAntRuntime="false">
			<classpath refid="lib.classpath" />
		</javac>

		<copy todir="${build}/META-INF">
			<fileset dir="${src}/META-INF" />
		</copy>

	</target>

	<target name="jar" depends="build">
		<jar jarfile="${dist}/${jarfile}" basedir="${build}">
			<manifest>
				<attribute name="Implementation-Title" value="${ant.project.name}" />
				<attribute name="Implementation-Version" value="${version}" />
				<attribute name="Built-By" value="${user.name}" />
			</manifest>
		</jar>
		<delete dir="${build}" />
	</target>

</project>
